### ISSUE TITLE
Something about the reinforcement learning

### ISSUE THREAD

**Issue by Tonyan** [Marsan-Ma/tf_chatbot_seq2seq_antilm#2]
I have trained in normal mode and got a decent model, but when I add the parameters --reinforce_learn  1, I find it does not work and get an error as "ValueError: Cannot feed value of shape (1, 1) for Tensor u'seq2seq/decoder19:0', which has shape '(1,)'  "
Thanks in Advance for the respond.

**Comment by ddvladimir** [comment]
Having same issue. 
Traced it down to **r3 = -self.logProb(session, args.buckets, resp_tokens, ep_encoder_inputs[-1])**
To resolve it I have introduced ep_tokens variable to which previous resp_tokens values are assigned. 
Then r3 calculation will look like that:
**r3 = -self.logProb(session, args.buckets, resp_tokens, ep_tokens[-1])**
That was done looking at the signature of **logProb** (expects two token arrays) and reading linked paper regarding reinforced learning. 

Couple of other modifications in order to make reinforce learning run:
1) Replaced  **r2 = -log(r2)**  with    **r2 = -log(abs(r2))** as r2 can be negative
2) in **logits2tokens** method replaced  **txt = [rev_vocab[t] for t in tokens]** with
 **txt = [rev_vocab[t] for t in tokens if t < len(rev_vocab)]** to avoid index out of range error

As a result there no exceptions, but performance is poor, most probably due to the changes I have introduced not 100% correct. (target was to make it run)

Would appreciate any feedback/fixes for this issue.

**Comment by Marsan-Ma** [comment]
this error could happen when you run out of gpu memory (if you didn't modify any code critical, this should be it)

As for 2, you could try to reduce the size of your graph by modifying params in config.py. 
Note that you still have to train a normal model in updated size again, before activating reinforcement-learning.

**Comment by loveJasmine** [comment]
still got the Error on the latest code

ValueError: Cannot feed value of shape (1, 1) for Tensor 'seq2seq/decoder1:0', which has shape '(?,)'

with the suggest change like:

diff --git a/lib/seq2seq_model.py b/lib/seq2seq_model.py
index 383bb99..03d610b 100644
--- a/lib/seq2seq_model.py
+++ b/lib/seq2seq_model.py
@@ -331,7 +331,9 @@ class Seq2SeqModel(object):
     while True:
       #----[Step]----------------------------------------
       encoder_state, step_loss, output_logits = self.step(session, encoder_inputs, decoder_inputs, target_weights,
-                          bucket_id, training=False, force_dec_input=False)
+                          bucket_id, forward_only=True, force_dec_input=False)
+
+      print("output_logits is:", output_logits)
       
       # memorize inputs for reproducing curriculum with adjusted losses
       ep_encoder_inputs.append(encoder_inputs)
@@ -361,7 +363,7 @@ class Seq2SeqModel(object):
       else:
         vec_a, vec_b = enc_states[-2], enc_states[-1]
         r2 = sum(vec_a*vec_b) / sum(abs(vec_a)*abs(vec_b))
-        r2 = -log(r2)
+        r2 = -log(abs(r2))
       
       # r3: Semantic Coherence
       r3 = -self.logProb(session, args.buckets, resp_tokens, ep_encoder_inputs[-1])
@@ -395,7 +397,7 @@ class Seq2SeqModel(object):
 
     # step
     _, _, output_logits = self.step(session, encoder_inputs, decoder_inputs, target_weights,
-                        bucket_id, training=False, force_dec_input=True)
+                        bucket_id, forward_only=False, force_dec_input=True)
     
     # p = log(P(b|a)) / N
     p = 1
@@ -413,12 +415,13 @@ class Seq2SeqModel(object):
     if data_utils.EOS_ID in tokens:
       eos = tokens.index(data_utils.EOS_ID)
       tokens = tokens[:eos]
-    txt = [rev_vocab[t] for t in tokens]
+    txt = [rev_vocab[t] for t in tokens if t < len(rev_vocab)]
     if sent_max_length:
       tokens, txt = tokens[:sent_max_length], txt[:sent_max_length]
     return tokens, txt
 
 
+
   def discount_rewards(self, r, gamma=0.99):
     """ take 1D float array of rewards and compute discounted reward """
     discounted_r = np.zeros_like(r)
