### ISSUE TITLE
beam search slow down factor

### ISSUE THREAD

**Issue by gidim** [Marsan-Ma/tf_chatbot_seq2seq_antilm#5]
Hey,

I was wondering if you know how much does the out of graph beam search slows this model down in training?

btw this is one of the best TF model/code that i've seen a while in terms of readability
and configuration options.

**Comment by Marsan-Ma** [comment]
Hi Gidim,

Yes, you are right. Since:

1. The beam search algorithm will grow the computing complexity by "your beam size" times.
Usually, I will not let beam_size over 30 in generating responses, and that's good enough. A larger beam_size doesn't do much better in dataset I've tried.

2. The beam search is built out-of-graph, which means the beam search can't be accelerated by GPU power, thus it's very slow. (please see the first item in TODOs).

Thank you!
